name: "Deploy to GitHub NuGet"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "Tag: $TAG"
          echo "Version: $VERSION"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Inject version into .csproj
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ steps.get_version.outputs.version }}</Version>|" workshop.calculator/workshop.calculator.csproj

      - name: Configure GitHub NuGet source
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/uerbzr/index.json \
            --name github \
            --username uerbzr \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore workshop.calculator/workshop.calculator.csproj

      - name: Build project
        run: dotnet build workshop.calculator/workshop.calculator.csproj --configuration Release

      - name: Pack NuGet package
        run: dotnet pack workshop.calculator/workshop.calculator.csproj --configuration Release --output ./nupkgs

      - name: Push package to GitHub NuGet feed
        run: dotnet nuget push ./nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: Release ${{ steps.get_version.outputs.tag }}
          body: |
            🎉 Release ${{ steps.get_version.outputs.version }} of workshop.calculator
            🔢 NuGet Package: uerbzr.workshop.calculator
            📦 Version: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
